
export const EndPoints = {
  BASE_URL: '',
  EXAMPLES: '/examples',
  PAGINATED_EXAMPLES: '/paginatedExamples',
  AUTH: '/authadmin',
  NOTIFICATION_CHANNELS: '/notificationchannels',
  CITIES: 'cities',
  REGIONS: '/regions',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  PrivacyPolicy: '/privacy-policy',
  ABOUT_US: 'about-us',
  SUB_SERVICE: 'sub-service',
  EVENT_TYPE: 'event-types',
  MAINSERVICE: '/mainservice',
  NEWS: '/News',
  SUB_SERVICE_STEP: '/sub-service-step',
  UserProfile: '/user-profile',
  FAQ: '/faqs',
  ESERVICE: '/eservice',
  EVENT: '/event',
  EVENT_IMAGES: '/event-images',
  ContactUsInfo: '/ContactUsInfo',
  ContactUsWorkTime: '/ContactUsWorkTime',
  JOB: '/Job',
  NEWSLETTER: '/newsletter',
  APPLY_JOB: '/ApplyJob',
  QUALIFIQATIN: '/Qualification',
  NATIONALITY: '/EnumValue/nationalities',
  APPLY_CV: '/CVS',
  CONTACT_US_MESSAGE: '/contact-us',
  MESSAGE_TYPE: '/InquiryType',
  STATUS: '/status/SplitedbyCommaIds',
  Social_Media_Links: '/social_links',
  HOME_PAGE_SETTING: '/page-setting',
  SUBSCRIBE: '/subscribe',
  MESSAGETYPE: '/message-types',
  FEEDBACK_RESULT: '/feedback-result',
  FEEDBACK: '/feedback',
  MAIL_TEMPLATE: '/mail-template',
  SURVEY: '/survey',
  SURVEY_QUESTION: '/mail-survey_question',
  RATE: '/rate',
  STATICS_RATE: '/rate/GetRateStatistics',
  Add_USER: '/user-profile',
  FEEDBACK_POSITIVE_NEGATIVE: '/EnumValue/GetAllGlopalLockup',
  OPEN_DATA_LIBRARY: '/open-data-request',
  GET_ALL_GLOPAL_LOOKUP: '/EnumValue/GetAllGlopalLockup',
  SERVICE_FEES: '/service-fees',
  REPORT: '/reports',
  OPEN_DATA: '/open-data',
  COUNTRIES: 'countries',
  ENUM_VALUE: '/EnumValue',
};

export type EndpointsType = typeof EndPoints;
